#!/bin/bash
#

# 03.04.2015

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  

#################################################################
# !!!! Manjaro Pek Tean								            #
# Write and improved by pekman									#
# Contact and sugestions: pekman@openmailbox.org                #
# Freenode: #manjaropek #manjaro-br #manjaro					#
# Topic discussion 							                    #
#																#
#																#
#################################################################


mkdir -p $HOME/Ffscreen
mkdir -p /tmp/.ffscreen_work

INPUT=default:CARD=MID

ffmpeg -f alsa -i $INPUT /tmp/.ffscreen_work/out-`date +%d-%m-%Y_%H:%M:%S`.wav -f x11grab -r 30 -s `xdpyinfo | grep 'dimensions:'|awk '{print $2}'` -i :0.0  -an -vcodec libx264 -preset ultrafast -qp 0 -threads 0 /tmp/.ffscreen_work/screencast-`date +%d-%m-%Y_%H:%M:%S`.mkv
	
cd /tmp/.ffscreen_work; ffmpeg -i *.mkv -i *.wav -map 0 -map 1 -c:v copy -c:a aac -strict -2 screencast-`date +%d-%m-%Y_%H:%M:%S`.mp4;rm *.wav *.mkv; HandBrakeCLI -i *.mp4 -o screencast-`date +%d-%m-%Y_%H:%M:%S`.mkv -m -E copy --audio-copy-mask ac3,dts,dtshd --audio-fallback ffac3 -e x264 -q 20 -x level=4.1:ref=4:b-adapt=2:direct=auto:me=umh:subq=8:rc-lookahead=50:psy-rd=1.0,0.15:deblock=-1,-1:vbv-bufsize=30000:vbv-maxrate=40000:slices=4; rm *.mp4; mv *.mkv $HOME/Ffscreen
